"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { featuredRun, keyAccounts } from "../lib/report-data";
import { copy, Locale, route } from "../lib/i18n";
import { SiteHeader } from "./SiteHeader";

export type RunRecord = { id:string; storyUrl:string; title:string; keyword:string; accounts?:string[]; status:string; visiblePosts:number; reportedPosts:string; totalImpressions?:number; createdAt:string };
export function Dashboard({locale}:{locale:Locale}) {
  const t=copy[locale]; const [runs,setRuns]=useState<RunRecord[]>([]); const [message,setMessage]=useState(""); const [submitting,setSubmitting]=useState(false);
  useEffect(()=>{fetch("/api/runs").then(r=>r.json()).then(d=>setRuns(d.runs??[])).catch(()=>setRuns([]))},[]);
  async function submitRun(event:FormEvent<HTMLFormElement>){event.preventDefault();setSubmitting(true);setMessage("");const form=new FormData(event.currentTarget);const accounts=String(form.get("accounts")??"").split(/[\s,]+/).filter(Boolean);const response=await fetch("/api/runs",{method:"POST",headers:{"content-type":"application/json","accept-language":locale},body:JSON.stringify({storyUrl:form.get("storyUrl"),keyword:form.get("keyword"),accounts})});const data=await response.json();setSubmitting(false);if(!response.ok)return setMessage(data.error??t.failed);setRuns(current=>[data.run,...current]);setMessage(t.queued);}
  return <main><SiteHeader locale={locale}/>
    <section className="hero grid-lines"><div className="eyebrow">{t.eyebrow}</div><h1>{t.title}<br/><span>{t.subtitle}</span></h1><p className="hero-note"><b>{t.note}</b></p><div className="issue-stamp">OPEN DESK<br/><span>2026</span></div></section>
    <section className="control-grid"><div className="panel input-panel"><div className="panel-label red">{t.newRun}</div><form onSubmit={submitRun}><label htmlFor={`${locale}-story-url`}><strong>{t.storyUrl}</strong></label><input id={`${locale}-story-url`} name="storyUrl" required defaultValue={featuredRun.storyUrl}/><label htmlFor={`${locale}-keyword`}><strong>{t.keyword}</strong></label><input id={`${locale}-keyword`} name="keyword" required defaultValue="Spark Lab"/><label htmlFor={`${locale}-accounts`}><strong>{t.accounts}</strong></label><textarea id={`${locale}-accounts`} name="accounts" rows={4} defaultValue={keyAccounts.join("\n")}/><button disabled={submitting} type="submit">{submitting?t.queuing:t.queue}</button><p className="form-note">{t.worker}</p>{message&&<p className="message">{message}</p>}</form></div>
    <div className="panel workflow-panel"><div className="panel-label blue">{t.workflow}</div>{t.steps.map((step,index)=><div className="workflow-row" key={step}><span className="step-no">0{index+1}</span><div><strong>{step}</strong><small>{t.stepNotes[index]}</small></div><span className={`status-dot ${index<3?"done":"warn"}`}>{index<3?"●":"◐"}</span></div>)}</div></section>
    <section className="feature-run"><div className="panel-label violet">{t.audit}</div><div className="feature-title"><div><span className="mono">STORY {featuredRun.storyId}</span><h2>{locale==="en"?featuredRun.title:featuredRun.titleZh}</h2></div><Link href={`${route(locale,"/report")}?run=${featuredRun.id}`} className="big-link">{t.openReport}</Link></div><div className="metric-strip"><div><em>1.3k</em><strong>{t.reported}</strong></div><div><em>137</em><strong>{t.visible}</strong></div><div><em>1,019,573</em><strong>{t.impressions}</strong></div><div><em className="red-text">+7</em><strong>{locale==="en"?"Found via accounts":"账号扫描补充"}</strong></div></div><div className="caveat">{t.caveat}</div></section>
    <section className="archive-preview"><div className="section-head"><strong>{t.recent}</strong><Link href={route(locale,"/records")}>{t.allRecords}</Link></div>{runs.length?runs.slice(0,4).map((run,index)=><RunRow key={run.id} run={run} index={index} locale={locale}/>):<p>{t.loading}</p>}</section><footer><span>METHOD BEFORE METRIC</span><span>X/STORY INDEX</span><span>{locale.toUpperCase()}</span></footer></main>;
}
export function RunRow({run,index,locale}:{run:RunRecord;index:number;locale:Locale}) { return <div className="record-row"><span>{String(index+1).padStart(2,"0")}</span><div><b>{run.title}</b><small>{run.keyword} · {run.visiblePosts} {copy[locale].visible} · {run.reportedPosts} {copy[locale].reported}</small></div><span className={`tag ${run.status}`}>{run.status}</span><time>{new Date(run.createdAt).toLocaleDateString(locale==="zh"?"zh-CN":"en-CA")}</time>{run.status==="audited"||run.status==="complete"?<Link className="row-link" href={`${route(locale,"/report")}?run=${run.id}`}>↗</Link>:null}</div> }
