"use client";
import { useEffect, useMemo, useState } from "react";
import { featuredRun, sparkPosts, topPosts } from "../lib/report-data";
import { Locale } from "../lib/i18n";
import { SiteHeader } from "./SiteHeader";
import type { RunRecord } from "./Dashboard";

type Post={id:string;author:string;text?:string;textZh?:string;impressions:number;likes:number;replies:number;reposts?:number;matchesKeyword?:boolean};
type ReportRun=RunRecord&{likes?:number;replies?:number;reposts?:number;sparkPosts?:number;sparkImpressions?:number;coveragePercent?:number;completedAt?:string};
const format=(value:number|undefined)=>new Intl.NumberFormat("en-US").format(value??0);
const labels={en:{label:"ANALYSIS REPORT",title:"Visible signals, measured limits.",collected:"Collected",reported:"Reported corpus",visible:"Visible posts",impressions:"Impressions",likes:"Likes",replies:"Replies",coverage:"Coverage",coverageNote:"Share of X's reported corpus exposed through the audited timelines.",distribution:"Impression distribution",top:"Top posts by impressions",spark:"Keyword signal",downloads:"Download evidence",csv:"RAW CSV ↓",json:"DATA JSON ↓",md:"REPORT ↓",method:"Method & scope",pending:"This run is queued. Its report will appear after the authenticated collector uploads results.",post:"POST",author:"AUTHOR",summary:"SUMMARY",engagement:"Engagement mix"},zh:{label:"分析报告",title:"可见信号，明确边界。",collected:"采集时间",reported:"卡片标注总量",visible:"可见帖子",impressions:"曝光量",likes:"点赞",replies:"评论",coverage:"覆盖率",coverageNote:"审计时间线向采集账号展示的帖子占 X 卡片标注总量的比例。",distribution:"曝光量分布",top:"按曝光量排序的头部帖子",spark:"关键词信号",downloads:"下载证据",csv:"原始 CSV ↓",json:"数据 JSON ↓",md:"报告 ↓",method:"方法与口径",pending:"该任务正在排队。登录态采集器上传结果后，报告会自动显示。",post:"帖子",author:"作者",summary:"摘要",engagement:"互动构成"}} as const;

export function Report({locale}:{locale:Locale}){const t=labels[locale];const[run,setRun]=useState<ReportRun>(featuredRun);const[posts,setPosts]=useState<Post[]>(topPosts);const runId=typeof window==="undefined"?featuredRun.id:new URLSearchParams(window.location.search).get("run")??featuredRun.id;
 useEffect(()=>{if(runId===featuredRun.id)return;fetch(`/api/runs?id=${encodeURIComponent(runId)}`).then(r=>r.json()).then(async d=>{if(d.run){setRun(d.run);if(d.run.status==="complete"||d.run.status==="audited"){const raw=await fetch(`/api/download?runId=${encodeURIComponent(runId)}&format=json`);if(raw.ok){const data=await raw.json();setPosts(data.posts??[])}}}}).catch(()=>{})},[runId]);
 const sorted=useMemo(()=>[...posts].sort((a,b)=>b.impressions-a.impressions),[posts]);const max=Math.max(1,...sorted.map(p=>p.impressions));const complete=run.status==="complete"||run.status==="audited";const impressions=run.totalImpressions??featuredRun.totalImpressions;const sparkCount=run.sparkPosts??sparkPosts.length;const sparkViews=run.sparkImpressions??sparkPosts.reduce((s,p)=>s+p.impressions,0);const coverage=run.coveragePercent??10;
 return <main><SiteHeader locale={locale} path="/report"/><div className="page-shell"><section className="page-intro report-intro"><div><span className="panel-label violet">{t.label}</span><h1>{t.title}</h1></div><p><b>{run.title}</b><br/>{t.collected}: {new Date(run.completedAt??run.createdAt).toLocaleString(locale==="zh"?"zh-CN":"en-GB")}</p></section>{!complete?<section className="pending-card"><span className="status-pulse"/><h2>{run.status.toUpperCase()}</h2><p>{t.pending}</p></section>:<>
 <section className="report-kpis"><div><b>{run.reportedPosts}</b><small>{t.reported}</small></div><div><b>{format(run.visiblePosts)}</b><small>{t.visible}</small></div><div><b>{format(impressions)}</b><small>{t.impressions}</small></div><div><b>{format(run.likes??featuredRun.likes)}</b><small>{t.likes}</small></div><div><b>{format(run.replies??featuredRun.replies)}</b><small>{t.replies}</small></div></section>
 <section className="viz-grid"><article className="viz-card"><div className="chart-head"><h2>{t.coverage}</h2><b>{coverage.toFixed(1)}%</b></div><div className="donut" style={{"--coverage":`${coverage*3.6}deg`} as React.CSSProperties}><span>{format(run.visiblePosts)}<small>/ {run.reportedPosts}</small></span></div><p>{t.coverageNote}</p></article><article className="viz-card"><div className="chart-head"><h2>{t.engagement}</h2><b>{format((run.likes??featuredRun.likes)+(run.replies??featuredRun.replies)+(run.reposts??featuredRun.reposts))}</b></div><div className="stacked"><span style={{width:"84%"}}/><span style={{width:"12%"}}/><span style={{width:"4%"}}/></div><div className="legend"><span><i className="blue-dot"/>{t.likes}</span><span><i className="red-dot"/>{t.replies}</span><span><i className="violet-dot"/>Reposts</span></div><div className="keyword-box"><b>{run.keyword}</b><strong>{sparkCount} posts · {format(sparkViews)} {t.impressions.toLowerCase()}</strong></div></article></section>
 <section className="report-section"><h2>{t.distribution}</h2><div className="histogram">{sorted.slice(0,12).map(post=><div key={post.id} title={`${post.author}: ${format(post.impressions)}`}><span style={{height:`${Math.max(4,post.impressions/max*100)}%`}}/><small>{post.author.replace("@","").slice(0,7)}</small></div>)}</div></section>
 <section className="report-section"><h2>{t.top}</h2><div className="rank-list">{sorted.slice(0,8).map((post,index)=><div className="rank-row" key={post.id}><span>{String(index+1).padStart(2,"0")}</span><div><b>{post.author}</b><small>{locale==="zh"?(post.textZh??post.text):(post.text??post.textZh)}</small><i style={{width:`${post.impressions/max*100}%`}}/></div><strong>{format(post.impressions)}</strong></div>)}</div></section>
 <section className="report-section"><h2>{t.downloads}</h2><div className="download-row"><a href={`/api/download?runId=${encodeURIComponent(runId)}&format=csv`}>{t.csv}</a><a href={`/api/download?runId=${encodeURIComponent(runId)}&format=json`}>{t.json}</a><a href={`/api/download?runId=${encodeURIComponent(runId)}&format=report&locale=${locale}`}>{t.md}</a></div></section>
 <section className="report-section method-note"><h2>{t.method}</h2><p>{locale==="en"?"Top and Latest timelines are scrolled to their visible end, merged by post ID, and snapshotted with public metrics. Reported corpus and visible sample are shown separately.":"Top 与 Latest 时间线滚动至可见末端后按帖子 ID 合并去重，并保存公开指标快照。卡片标注总量与页面可见样本始终分开呈现。"}</p></section></>}</div><footer><span>VISIBLE SAMPLE</span><span>METHOD BEFORE METRIC</span><span>{locale.toUpperCase()}</span></footer></main>}
