import Link from "next/link";
import {featuredRun,sparkPosts,topPosts} from "../lib/report-data";
const format=(value:number)=>new Intl.NumberFormat("en-US").format(value);
export default function ReportPage(){return <main><header className="masthead"><Link href="/" className="brand">X/STORY INDEX</Link><nav><Link href="/records">RECORDS / 记录</Link><Link href="/report">REPORT / 报告</Link></nav></header><div className="page-shell">
<section className="page-intro"><div><span className="panel-label violet">REPORT 001 · 报告 001</span><h1>Visible signals,<br/><span>visible limits.</span></h1></div><p><b>{featuredRun.title}</b><br/><span className="zh">{featuredRun.titleZh}</span><br/><br/>Collected Aug 11, 2026 · 采集于 2026 年 8 月 11 日</p></section>
<section className="report-kpis"><div><b>1.3k</b><small>Reported corpus<br/><span className="zh">卡片标注总量</span></small></div><div><b>130</b><small>Visible posts<br/><span className="zh">可见帖子</span></small></div><div><b>1,015,945</b><small>Impressions<br/><span className="zh">样本曝光</span></small></div><div><b>5,878</b><small>Likes<br/><span className="zh">点赞</span></small></div><div><b>834</b><small>Replies<br/><span className="zh">评论</span></small></div></section>
<section className="report-section"><span className="panel-label red">COVERAGE · 覆盖范围</span><div className="coverage-bar"><span/></div><p><b>Approximately 10% of the reported corpus is visible through Top + Latest.</b><br/><span className="zh">Top + Latest 仅展示卡片标注语料的约 10%。</span></p><p>The 130-post dataset is a reproducible visible sample, not the complete 1.3k corpus. X does not expose the remaining cluster through the Story timelines used in this audit.<br/><span className="zh">130 条数据是可复核的页面可见样本，而非完整 1.3k 语料；本次审计所用 Story 时间线没有公开其余关联帖子。</span></p></section>
<section className="report-section"><h2>Findings <span className="zh">主要发现</span></h2>{["Top 10 posts account for 91.61% of sample impressions.|前 10 条帖子贡献样本曝光的 91.61%。","Median impressions are 207 versus a mean of 7,815.|曝光中位数为 207，均值为 7,815，呈明显长尾。","Three visible cards match Spark Lab, totaling 2,808 impressions.|3 条可见卡片匹配 Spark Lab，合计 2,808 次曝光。","Strict body-only matching finds one post and 526 impressions.|若仅匹配正文，则为 1 条帖子、526 次曝光。"].map((item,index)=>{const[en,zh]=item.split("|");return <div className="finding" key={en}><span>0{index+1}</span><div><b>{en}</b><span className="zh">{zh}</span></div></div>})}</section>
<section className="report-section"><h2>Top posts <span className="zh">头部帖子</span></h2><table className="data-table"><thead><tr><th>POST / 帖子</th><th>AUTHOR / 作者</th><th>SUMMARY / 摘要</th><th>IMPRESSIONS / 曝光</th><th>LIKES / 点赞</th><th>REPLIES / 评论</th></tr></thead><tbody>{topPosts.map(post=><tr key={post.id}><td><a href={`https://x.com/i/status/${post.id}`} target="_blank" rel="noreferrer">{post.id.slice(-6)} ↗</a></td><td>{post.author}</td><td><b>{post.text}</b><br/><span className="zh">{post.textZh}</span></td><td className="num">{format(post.impressions)}</td><td className="num">{format(post.likes)}</td><td className="num">{format(post.replies)}</td></tr>)}</tbody></table></section>
<section className="report-section"><h2>Spark Lab signals <span className="zh">Spark Lab 相关信号</span></h2><table className="data-table"><thead><tr><th>POST</th><th>AUTHOR / 作者</th><th>IMPRESSIONS / 曝光</th><th>LIKES / 点赞</th><th>REPLIES / 评论</th></tr></thead><tbody>{sparkPosts.map(post=><tr key={post.id}><td><a href={`https://x.com/i/status/${post.id}`} target="_blank" rel="noreferrer">{post.id} ↗</a></td><td>{post.author}</td><td className="num">{format(post.impressions)}</td><td className="num">{post.likes}</td><td className="num">{post.replies}</td></tr>)}</tbody></table></section>
<section className="report-section"><h2>Download evidence <span className="zh">下载证据</span></h2><div className="download-row"><a href="/data/x-story-posts.csv" download>CSV / 逐帖明细 ↓</a><a href="/data/x-story-snapshot.json" download>JSON / 原始快照 ↓</a></div></section>
<section className="report-section"><h2>Method <span className="zh">方法</span></h2><p><b>Top: 74 · Latest: 98 · Overlap: 42 · Unique: 130.</b><br/><span className="zh">两个标签均滚动至真实页面底部，并额外等待确认无加载状态。指标取自 X 页面公开 ARIA 标签，按 post ID 去重。</span></p></section>
</div><footer><span>VISIBLE SAMPLE / 可见样本</span><span>METHOD BEFORE METRIC / 方法先于指标</span><span>2026</span></footer></main>}
