import{env}from"cloudflare:workers";import{featuredRun}from"../app/lib/report-data";
const columns=[
  ["total_impressions","INTEGER NOT NULL DEFAULT 0"],["likes","INTEGER NOT NULL DEFAULT 0"],["replies","INTEGER NOT NULL DEFAULT 0"],["reposts","INTEGER NOT NULL DEFAULT 0"],["spark_posts","INTEGER NOT NULL DEFAULT 0"],["spark_impressions","INTEGER NOT NULL DEFAULT 0"],["coverage_percent","REAL NOT NULL DEFAULT 0"],["artifact_prefix","TEXT"],["completed_at","TEXT"],["watch_accounts","TEXT NOT NULL DEFAULT '[]'"],["account_found_posts","INTEGER NOT NULL DEFAULT 0"],
] as const;
export type RunResult={title:string;reportedPosts:string;posts:Array<{id:string;author:string;text?:string;impressions:number;likes:number;replies:number;reposts?:number;matchesKeyword?:boolean;source?:string}>};
export async function ensureRunsSchema(){const db=env.DB;await db.batch([db.prepare(`CREATE TABLE IF NOT EXISTS runs (id TEXT PRIMARY KEY, story_url TEXT NOT NULL, title TEXT NOT NULL, keyword TEXT NOT NULL, watch_accounts TEXT NOT NULL DEFAULT '[]', account_found_posts INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL, visible_posts INTEGER NOT NULL DEFAULT 0, reported_posts TEXT NOT NULL DEFAULT 'unknown', total_impressions INTEGER NOT NULL DEFAULT 0, likes INTEGER NOT NULL DEFAULT 0, replies INTEGER NOT NULL DEFAULT 0, reposts INTEGER NOT NULL DEFAULT 0, spark_posts INTEGER NOT NULL DEFAULT 0, spark_impressions INTEGER NOT NULL DEFAULT 0, coverage_percent REAL NOT NULL DEFAULT 0, artifact_prefix TEXT, created_at TEXT NOT NULL, completed_at TEXT)`),db.prepare(`CREATE INDEX IF NOT EXISTS idx_runs_created_at ON runs(created_at)`),db.prepare(`CREATE INDEX IF NOT EXISTS idx_runs_status ON runs(status)`)]);const info=await db.prepare(`PRAGMA table_info(runs)`).all<{name:string}>();const existing=new Set(info.results.map(row=>row.name));for(const[name,type]of columns){if(!existing.has(name))await db.prepare(`ALTER TABLE runs ADD COLUMN ${name} ${type}`).run()}await db.prepare(`INSERT OR IGNORE INTO runs (id, story_url, title, keyword, watch_accounts, account_found_posts, status, visible_posts, reported_posts, total_impressions, likes, replies, reposts, spark_posts, spark_impressions, coverage_percent, artifact_prefix, created_at, completed_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).bind(featuredRun.id,featuredRun.storyUrl,featuredRun.title,featuredRun.keyword,JSON.stringify(featuredRun.accounts),7,featuredRun.status,featuredRun.visiblePosts,featuredRun.reportedPosts,featuredRun.totalImpressions,featuredRun.likes,featuredRun.replies,featuredRun.reposts,featuredRun.sparkPosts,featuredRun.sparkImpressions,featuredRun.coveragePercent,`runs/${featuredRun.id}`,featuredRun.createdAt,featuredRun.createdAt).run();await db.prepare(`UPDATE runs SET watch_accounts=?, account_found_posts=7, visible_posts=?, total_impressions=?, likes=?, replies=?, reposts=?, spark_posts=?, spark_impressions=?, coverage_percent=?, artifact_prefix=?, completed_at=? WHERE id=?`).bind(JSON.stringify(featuredRun.accounts),featuredRun.visiblePosts,featuredRun.totalImpressions,featuredRun.likes,featuredRun.replies,featuredRun.reposts,featuredRun.sparkPosts,featuredRun.sparkImpressions,featuredRun.coveragePercent,`runs/${featuredRun.id}`,featuredRun.createdAt,featuredRun.id).run()}
const select=`SELECT id, story_url AS storyUrl, title, keyword, watch_accounts AS watchAccounts, account_found_posts AS accountFoundPosts, status, visible_posts AS visiblePosts, reported_posts AS reportedPosts, total_impressions AS totalImpressions, likes, replies, reposts, spark_posts AS sparkPosts, spark_impressions AS sparkImpressions, coverage_percent AS coveragePercent, artifact_prefix AS artifactPrefix, created_at AS createdAt, completed_at AS completedAt FROM runs`;
export async function listRuns(){await ensureRunsSchema();const result=await env.DB.prepare(`${select} ORDER BY created_at DESC LIMIT 100`).all();return result.results}
export async function getRun(id:string){await ensureRunsSchema();return env.DB.prepare(`${select} WHERE id=?`).bind(id).first()}
export async function createRun(storyUrl:string,keyword:string,accounts:string[]){await ensureRunsSchema();const id=`run_${crypto.randomUUID()}`;const createdAt=new Date().toISOString();const title="Queued X Story audit";await env.DB.prepare(`INSERT INTO runs (id, story_url, title, keyword, watch_accounts, status, visible_posts, reported_posts, created_at) VALUES (?, ?, ?, ?, ?, 'queued', 0, 'unknown', ?)`).bind(id,storyUrl,title,keyword,JSON.stringify(accounts),createdAt).run();return{id,storyUrl,title,keyword,accounts,status:"queued",visiblePosts:0,reportedPosts:"unknown",totalImpressions:0,createdAt}}
function reportedNumber(value:string){const match=value.toLowerCase().match(/^([\d.]+)\s*([km])?$/);if(!match)return 0;const base=Number(match[1]);return Math.round(base*(match[2]==="k"?1000:match[2]==="m"?1000000:1))}
export async function completeRun(id:string,result:RunResult){await ensureRunsSchema();const run=await getRun(id)as{keyword?:string}|null;if(!run)throw new Error("Run not found");const key=(run.keyword??"").toLowerCase();const totals=result.posts.reduce((a,p)=>({impressions:a.impressions+(p.impressions||0),likes:a.likes+(p.likes||0),replies:a.replies+(p.replies||0),reposts:a.reposts+(p.reposts||0),sparkPosts:a.sparkPosts+(p.matchesKeyword||p.text?.toLowerCase().includes(key)?1:0),sparkImpressions:a.sparkImpressions+(p.matchesKeyword||p.text?.toLowerCase().includes(key)?p.impressions||0:0),accountFoundPosts:a.accountFoundPosts+(p.source==="key-account"?1:0)}),{impressions:0,likes:0,replies:0,reposts:0,sparkPosts:0,sparkImpressions:0,accountFoundPosts:0});const reported=reportedNumber(result.reportedPosts);const coverage=reported?result.posts.length/reported*100:0;const completedAt=new Date().toISOString();const prefix=`runs/${id}`;await env.DB.prepare(`UPDATE runs SET title=?, status='complete', visible_posts=?, reported_posts=?, total_impressions=?, likes=?, replies=?, reposts=?, spark_posts=?, spark_impressions=?, account_found_posts=?, coverage_percent=?, artifact_prefix=?, completed_at=? WHERE id=?`).bind(result.title,result.posts.length,result.reportedPosts,totals.impressions,totals.likes,totals.replies,totals.reposts,totals.sparkPosts,totals.sparkImpressions,totals.accountFoundPosts,coverage,prefix,completedAt,id).run();return{...(await getRun(id)),posts:result.posts}}
